config/routes.rb
Rails.application.routes.draw do

  devise_for :players, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }, module: "players", :controllers => { :omniauth_callbacks => "players/omniauth_callbacks" }
  root to: "home#index"
  get '/tournaments' => "tournaments#main", as: "tournament_index"
  get '/tournaments/create' => "tournaments#index", as: "tournament_create"
  get '/tournaments/show' => "tournaments#show", as: "tournament_show_all"
  get '/tournaments/:id/init', :controller => 'tournaments', :action => 'init', as: "tournament_init"
  post '/tournaments/:id/start', :controller => 'tournaments', :action => 'start', as: "tournament_start"
  post '/tournaments/new', :controller => 'tournaments', :action => 'create', as: "tournament_new"
  get '/tournaments/:id/play' => "tournaments#play", as: "tournament_play"
  post '/tournaments/:id/play/match', :controller => 'tournaments', :action => 'match_finished'
  get '/tournaments/:id/finish' => "tournaments#finish", as: "tournament_summary"
  get '/tournaments/:id/play/final' => 'tournaments#final', as: "tournament_final_match"
  post '/tournaments/:id/final', :controller => 'tournaments', :action => 'final_match'
  post '/tournaments/:id/end', :controller => 'tournaments', :action => 'destroy', as: "tournament_destroy"
  get '/tournaments/:id/join' => "tournaments#join", as: "tournament_join"
  get '/tournaments/:id/owner_join' => "tournaments#owner_join", as: "tournament_owner_join"
  post '/tournaments/:id/join_owner', :controller => "tournaments", :action => "join_owner", as: "tournament_join_owner"
  post '/tournaments/:id/join', :controller => 'tournaments', :action => 'join_player', as: "tournament_join_player"
  get '/tournaments/:id/joined' => "tournaments#joined", as: "tournament_joined"
  get '/players/:id/history' => 'players#history', as: "player_history"

end

app/models/tournament.rb
class Tournament < ActiveRecord::Base
	has_many :player_infos
	has_many :players, through: :player_infos
	has_many :matches
	has_one :player, :foreign_key => 'winner_id'
end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController

  def join
    @tournament = Tournament.find(params[:id])
  end

  def show
    @tournaments = Tournament.all
  end

  def init
    @tournament = Tournament.find(params[:id])
    @user = current_player
  end

  def start
    tournament = Tournament.find(params[:id])
    players = params[:players]
    if(players.size >= tournament.minPlayers)
      for i in 0..tournament.players.size
        for j in i+1..tournament.players.size-1
          m = Match.new
          m.status = "Not Played"
          m.first_player = tournament.players[i]
          m.second_player = tournament.players[j]
          m.tournament = tournament
          m.save
        end
      end
      respond_to do |format|
        format.json do
          render json: {
            response: "success"
          }.to_json
        end
      end
    else
      respond_to do |format|
        format.json do
          render json: {
            response: "error",
            reason: "No hay suficientes jugadores"
          }.to_json
        end
      end
    end
  end

  def play
    @tournament = Tournament.find(params[:id])
    @matches = []
    Match.all.each do |match|
      if match.status == "Not Played" && match.tournament == @tournament
        matrix = [ [ match.first_player.username, PlayerInfo.find_by(player_id: match.first_player.id).team ], [ match.second_player.username, PlayerInfo.find_by(player_id: match.second_player.id).team ] ]
        @matches.push(matrix)
      end
    end
    @tournament.status = "Started"
    @tournament.save
    @players_info = PlayerInfo.where(tournament_id: @tournament.id).order(currentPoints: :desc)
    if( @matches.size < 1 )
      redirect_to tournament_final_match_path(params[:id])
    end
  end

  def create
    if(Tournament.find_by(name: params[:name]) == nil)
      t = Tournament.new
      t.name = params[:name]
      t.minPlayers = params[:min]
      t.status = "Created"
      t.save
      redirect_to tournament_owner_join_path(t.id), notice: "Torneo Creado"
    else
      redirect_to tournament_new_path, alert: "Error, Torneo ya existente"
    end
  end

  def match_finished
    first_player = Player.find_by(username: params[:first_player_name])
    second_player = Player.find_by(username: params[:second_player_name])
    first_player_info = PlayerInfo.find_by(player_id: first_player.id)
    second_player_info = PlayerInfo.find_by(player_id: second_player.id)
    match = Match.find_by(first_player_id: first_player.id, second_player_id: second_player.id, tournament_id: params[:id])
    if(params[:first_player] > params[:second_player])
      match.status = "Played"
      match.save
      first_player_info.currentPoints = first_player_info.currentPoints + 3
      first_player_info.save
      redirect_to tournament_play_path(params[:id]), notice: "Ganador: " + first_player.username
    elsif(params[:second_player] > params[:first_player])
      match.status = "Played"
      match.save
      second_player_info.currentPoints = second_player_info.currentPoints + 3
      second_player_info.save
      redirect_to tournament_play_path(params[:id]), notice: "Ganador: " + second_player.username
    elsif(params[:first_player] == params[:second_player])
      match.status = "Played"
      match.save
      first_player_info.currentPoints = first_player_info.currentPoints + 1
      second_player_info.currentPoints = second_player_info.currentPoints + 1
      first_player_info.save
      second_player_info.save
      redirect_to tournament_play_path(params[:id]), notice: "Empate"
    end
  end

  def finish
    @tournament = Tournament.find(params[:id])
    @players_info = PlayerInfo.where(tournament_id: @tournament.id).order(currentPoints: :desc)
    @tournament.winner_id = Player.find_by(username: params[:winner_name]).id
    @winner = params[:winner_name]
    @tournament.status = "Finished"
    @tournament.save
  end

  def final_match
    first_player = Player.find_by(username: params[:first_finalist_name])
    second_player = Player.find_by(username: params[:second_finalist_name])
    first_player_info = PlayerInfo.find_by(player_id: first_player.id)
    second_player_info = PlayerInfo.find_by(player_id: second_player.id)
    if(params[:second_finalist_score] > params[:first_finalist_score])
      redirect_to tournament_summary_path(params[:id], winner_name: second_player.username)
    end
    if(params[:first_finalist_score] > params[:second_finalist_score])
      redirect_to tournament_summary_path(params[:id], winner_name: first_player.username)
    end
    if(params[:first_finalist_score] == params[:second_finalist_score])
      redirect_to tournament_final_match_path(params[:id])
    end
  end

  def final
    @tournament = Tournament.find(params[:id])
    @players_info = PlayerInfo.where(tournament_id: @tournament.id).order(currentPoints: :desc)
  end

  def destroy
    tournament = Tournament.find(params[:id])
    tournament.save
    redirect_to tournament_index_path, notice: "Torneo Terminado"
  end

  def join_player
    current_player.player_infos.build(team: params[:team], currentPoints: 0, tournament_id: params[:id])
    current_player.save
    redirect_to tournament_joined_path(params[:id])
  end

  def owner_join
    @tournament = Tournament.find(params[:id])    
  end

  def join_owner
    current_player.player_infos.build(team: params[:team], currentPoints: 0, tournament_id: params[:id])
    current_player.save
    redirect_to tournament_init_path(params[:id])
  end

end

app/helpers/tournaments_helper.rb
module TournamentsHelper
end

app/views/tournaments/final.html.erb
<h1 class="text-center"><%= @tournament.name %></h1>
<h2 class="text-center">Final</h2>
<div class="container">
  <%= form_tag("/tournaments/" + @tournament.id.to_s + "/final", method: "post") do %>
    <div class="row text-center">
      <div class="col-xs-5">
        <%= image_tag Player.find(@players_info[0].player_id).avatar.url(:thumb), class: "center-block" %>
        <h4><%=Player.find(@players_info[0].player_id).username%> (<%=@players_info[0].team%>)</h4>
        <%= hidden_field_tag(:first_finalist_name, Player.find(@players_info[0].player_id).username) %>
        <%= number_field_tag(:first_finalist_score, nil, {min: 0, required: "true", class: "text-center"}) %>
      </div>
      <div class="col-xs-2">
        <b>VS</b>
      </div>
      <div class="col-xs-5">
        <%= image_tag Player.find(@players_info[1].player_id).avatar.url(:thumb), class: "center-block" %>
        <h4><%=Player.find(@players_info[1].player_id).username%> (<%=@players_info[1].team%>)</h4>
        <%= hidden_field_tag(:second_finalist_name, Player.find(@players_info[1].player_id).username) %>
        <%= number_field_tag(:second_finalist_score, nil, {min: 0, required: "true", class: "text-center"}) %>
      </div>
    </div>
    <br>
    <%= submit_tag("Enviar Marcador", class: "btn btn-primary center-block") %>
  <% end %>
</div>

app/views/tournaments/finish.html.erb
<h1 class="text-center">Ganador de <%= @tournament.name %></h1>
<h2 class="text-center"><%= @winner %></h2>
<h4 class="text-center">¡Felicitaciones!</h4>
<div class="container">
  <table class="table table-striped table-bordered">
    <thead>
      <tr>
        <th class="text-center">
          #
        </th>
        <th class="text-center">
          Jugador
        </th>
        <th class="text-center">
          Equipo
        </th>
        <th class="text-center">
          Puntos
        </th>
      </tr>
    </thead>
    <br>
    <h3>Tabla de Puntuación</h3>
    <tbody>
      <% i = 1 %>
      <% @players_info.each do |player_info| %>
        <tr class="text-center">
          <td>
            <%= i %>
            <% i+=1 %>
          </td>
          <td>
            <%= Player.find(player_info.player_id).username %>
          </td>
          <td>
            <%= player_info.team %>
          </td>
          <td>
            <%= player_info.currentPoints %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= form_tag(tournament_destroy_path(@tournament.id), method: "post") do %>
    <%= submit_tag("Terminar Torneo", class: "btn btn-primary center-block") %>
  <% end %>
</div>

app/views/tournaments/index.html.erb
<h1 class="center-block text-center">Crear Torneo</h1>
<div class="container">
	<%= form_tag(tournament_new_path, method: "post") do %>
	  <%= label_tag(:name, "Nombre") %>
	  <%= text_field_tag(:name, nil, {class: "form-control", placeholder: "Nombre del torneo", required: "true"}) %>
		<%= label_tag(:min, "Minimo de jugadores:") %>
	  <%= number_field_tag(:min, 3, {class: "form-control", min: 3, required: "true"}) %>
		<br>
	  <%= submit_tag("Crear", class: "btn btn-primary center-block") %>
	<% end %>
</div>

app/views/tournaments/init.html.erb
<h1 class="text-center"><%= @tournament.name %></h1>
<div class="container">
  <h2 class="col-sm-6">Jugadores:</h2>
  <div class="col-sm-6 clear-fix">
    <!--<a href="javascript:add_player();" class="btn btn-primary center-block pull-right">Agregar otro jugador</a>-->
  </div>
  <form class="col-xs-12" action="javascript:init_tournament();" method="post">
    <div id="content" class="row">
      <% @tournament.players.each do |player| %>
        <div class="col-xs-12 element">
          <div class="col-xs-10">
            <label>Jugador:</label>
            <input type="text" value="<%= player.username %>" placeholder="Nombre del jugador" class="form-control" required disabled>
          </div>
          <div class="col-xs-2">
            <label>Equipo:</label>
            <input type="text" value="<%= PlayerInfo.find_by(player_id: player.id).team %>" class="form-control" required disabled>
          </div>
        </div>
      <% end %>
    </div>
    <br>
    <input type="submit" name="commit" class="btn btn-primary center-block" value="Empezar Torneo">
  </form>
</div>
<script>
  (function(){
    for (var i = 0; i < countries.length; i++) {
      $("select").each(function(){
        var flag = false;
        $(this).children("option").each(function(){
          if($(this).val() == countries[i]){
            flag = true;
          }
        });
        if(!flag){
          $(this).append("<option value='"+countries[i]+"'>"+countries[i]+"</option>");
        }
      });
    }
  })();

  function init_tournament(){
    var players = [];
    $(".element").each(function(){
      var info = [];
      info.push($(this).find("input[type='text']").val());
      info.push($(this).find("select option:selected").val());
      players.push(info);
    });
    $.ajax({
      type: "POST",
      url: "<%= tournament_start_path(@tournament.id) %>",
      data: { "players" : players },
      success: function(data){
        console.log(data);
        if(data.response == "success"){
          window.location.href = "<%= tournament_play_path(@tournament.id) %>"
        }
        if(data.response == "error"){
          alert(data.reason);
        }
      },
      error: function(e){
        alert("Error, intentalo de nuevo mas tarde")
      }
    });
  }
</script>

app/views/tournaments/join.html.erb
<h1 class="text-center"><%= @tournament.name %></h1>
<div class="container">
	<h3 class="text-center">Selecciona tu equipo</h3>
	<select class="form-control">
	</select>
	<br>
	<button class="btn btn-primary center-block" onclick="join_tournament();">Ingresar al torneo</button>
</div>
<script>
	(function(){
		for (var i = 0; i < countries.length; i++) {
			$("select").each(function(){
				var flag = false;
				$(this).children("option").each(function(){
					if($(this).val() == countries[i]){
						flag = true;
					}
				});
				if(!flag){
					$(this).append("<option value='"+countries[i]+"'>"+countries[i]+"</option>");
				}
			});
		}
	})();

	function join_tournament(){
		$.ajax({
			type: "POST",
			url: "<%= tournament_join_player_path(@tournament.id) %>",
			data: { "team" : $("select option:selected").val() },
			success: function(data){
				if(data.response == "success"){
					window.location.href= "<%= tournament_joined_path %>";
				}
			},
			error: function(e){
				alert("Error, intentelo de nuevo mas tarde");
			}
		});
	}
</script>

app/views/tournaments/joined.html.erb
<h1 class="text-center">¡Te has unido al torneo</h1>
<div class="container text-center">
	<span>Ahora el creador del torneo maneja la logica del mismo.</span>
	<h4>¡Disfruta del torneo!</h4>
	<%= link_to "Volver", tournament_index_path, class: "btn btn-primary" %>
</div

app/views/tournaments/main.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to "Inicio", tournament_index_path %></li>
        <!--<li>
          <%= link_to edit_player_password_path do %>
            Perfil
          <% end %>
        </li>-->
        <li><%= link_to "Historial", player_history_path(current_player.id) %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a>Sesión Iniciada como <b><%= current_player.username %></b></a></li>
        <li><%= link_to "Cerrar Sesión", destroy_player_session_path, method: "DELETE" %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<h1 class="text-center">Escoge una opción</h1>
<div class="container">
  <br>
  <%= link_to('Crear Torneo', tournament_create_path, { class: "btn-primary btn center-block" }) %>
  <br>
  <%= link_to('Unirse a Torneo', tournament_show_all_path, { class: "btn-primary btn center-block" }) %>
</div>

app/views/tournaments/owner_join.html.erb
<h1 class="text-center"><%= @tournament.name %></h1>
<div class="container">
	<h3 class="text-center">Selecciona tu equipo</h3>
	<select class="form-control">
	</select>
	<br>
	<button class="btn btn-primary center-block" onclick="join_tournament();">Ingresar al torneo</button>
</div>
<script>
	(function(){
		for (var i = 0; i < countries.length; i++) {
			$("select").each(function(){
				var flag = false;
				$(this).children("option").each(function(){
					if($(this).val() == countries[i]){
						flag = true;
					}
				});
				if(!flag){
					$(this).append("<option value='"+countries[i]+"'>"+countries[i]+"</option>");
				}
			});
		}
	})();

	function join_tournament(){
		$.ajax({
			type: "POST",
			url: "<%= tournament_join_owner_path(@tournament.id) %>",
			data: { "team" : $("select option:selected").val() },
			success: function(data){
				if(data.response == "success"){
					window.location.href= "<%= tournament_joined_path %>";
				}
			},
			error: function(e){
				alert("Error, intentelo de nuevo mas tarde");
			}
		});
	}
</script>

app/views/tournaments/play.html.erb
<h1 class="text-center">Torneo: <small><%= @tournament.name %></small></h1>
<div class="container">
  <div class="center-block">
    <h3>Partido Actual</h3>
    <%= form_tag("/tournaments/" + @tournament.id.to_s + "/play/match", method: "post") do %>
      <div class="row text-center">
        <div class="col-xs-5">
          <%= image_tag Player.find_by(username: @matches[0][0][0]).avatar.url(:thumb), class: "center-block" %>
          <h4><%=@matches[0][0][0]%> (<%=@matches[0][0][1]%>)</h4>
          <%= hidden_field_tag(:first_player_name, @matches[0][0][0]) %>
          <%= number_field_tag(:first_player, nil, {min: 0, required: "true", class: "text-center"}) %>
        </div>
        <div class="col-xs-2">
          <b>VS</b>
        </div>
        <div class="col-xs-5">
          <%= image_tag Player.find_by(username: @matches[0][1][0]).avatar.url(:thumb), class: "center-block" %>
          <h4><%=@matches[0][1][0]%> (<%=@matches[0][1][1]%>)</h4>
          <%= hidden_field_tag(:second_player_name, @matches[0][1][0]) %>
          <%= number_field_tag(:second_player, nil, {min: 0, required: "true", class: "text-center"}) %>
        </div>
      </div>
  		<br>
  	  <%= submit_tag("Enviar Marcador", class: "btn btn-primary center-block") %>
  	<% end %>
  </div>
  <br>
  <div class="center-block">
    <h3>Proximos Partidos</h3>
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th class="text-center">
            Jugador 1
          </th>
          <th class="text-center">
            Versus
          </th>
          <th class="text-center">
            Jugador 2
          </th>
        </tr>
      </thead>
      <tbody>
        <% for i in 1..@matches.size-1 %>
          <tr>
            <td class="text-center">
              <%= @matches[i][0][0] %> (<%= @matches[i][0][1] %>)
            </td>
            <td class="text-center">
              <b>VS</b>
            </td>
            <td class="text-center">
              <%= @matches[i][1][0] %> (<%= @matches[i][1][1] %>)
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th class="text-center">
            #
          </th>
          <th class="text-center">
            Jugador
          </th>
          <th class="text-center">
            Equipo
          </th>
          <th class="text-center">
            Puntos
          </th>
        </tr>
      </thead>
      <br>
      <h3>Tabla de Puntuación</h3>
      <tbody>
        <% i = 1 %>
        <% @players_info.each do |player_info| %>
          <tr class="text-center">
            <td>
              <%= i %>
              <% i+=1 %>
            </td>
            <td>
              <%= Player.find(player_info.player_id).username %>
            </td>
            <td>
              <%= player_info.team %>
            </td>
            <td>
              <%= player_info.currentPoints %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/tournaments/show.html.erb
<h1 class="text-center">Torneos Activos</h1>
<br>
<div class="container">
  <div class="list-group">
    <% @tournaments.each do |tournament| %>
      <% if tournament.status == "Created" %>
        <%= link_to(tournament.name, tournament_join_path(tournament.id), {class: 'list-group-item'}) %>
      <% end %>
    <%end %>
  </div>
</div>