config/routes.rb
Rails.application.routes.draw do

  devise_for :players, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }, module: "players", :controllers => { :omniauth_callbacks => "players/omniauth_callbacks" }
  root to: "home#index"
  get '/tournaments' => "tournaments#main", as: "tournament_index"
  get '/tournaments/create' => "tournaments#index", as: "tournament_create"
  get '/tournaments/show' => "tournaments#show", as: "tournament_show_all"
  get '/tournaments/:id/init', :controller => 'tournaments', :action => 'init', as: "tournament_init"
  post '/tournaments/:id/start', :controller => 'tournaments', :action => 'start', as: "tournament_start"
  post '/tournaments/new', :controller => 'tournaments', :action => 'create', as: "tournament_new"
  get '/tournaments/:id/play' => "tournaments#play", as: "tournament_play"
  post '/tournaments/:id/play/match', :controller => 'tournaments', :action => 'match_finished'
  get '/tournaments/:id/finish' => "tournaments#finish", as: "tournament_summary"
  get '/tournaments/:id/play/final' => 'tournaments#final', as: "tournament_final_match"
  post '/tournaments/:id/final', :controller => 'tournaments', :action => 'final_match'
  post '/tournaments/:id/end', :controller => 'tournaments', :action => 'destroy', as: "tournament_destroy"
  get '/tournaments/:id/join' => "tournaments#join", as: "tournament_join"
  get '/tournaments/:id/owner_join' => "tournaments#owner_join", as: "tournament_owner_join"
  post '/tournaments/:id/join_owner', :controller => "tournaments", :action => "join_owner", as: "tournament_join_owner"
  post '/tournaments/:id/join', :controller => 'tournaments', :action => 'join_player', as: "tournament_join_player"
  get '/tournaments/:id/joined' => "tournaments#joined", as: "tournament_joined"
  get '/players/:id/history' => 'players#history', as: "player_history"

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1 class="text-center">Torneos de Fifa - Fuse Pong</h1>
<div class="container">
  <div class="col-xs-6 col-xs-offset-3">
    <h3 class="text-center">Empieza a jugar</h3>
    <%= link_to("Inicia Sesión", new_player_session_path(), class: "btn btn-primary center-block") %>
    <br>
    <%= link_to "Inicia Sesión con Facebook", player_facebook_omniauth_authorize_path, class: "btn btn-primary center-block" %>
    <!--<br>
    <%= link_to "Inicia Sesión con Twitter", player_twitter_omniauth_authorize_path, class: "btn btn-primary center-block" %>-->
    <h4 class="text-center">ó</h4>
    <%= link_to("Registrate", new_player_registration_path(), class: "btn btn-primary center-block") %>
  </div>
</div>